Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/cpnbomexport.py", line 24, in <module>
    logging.basicConfig(filename=('./restapi.log'), filemode='w', level=logging.DEBUG, format='%(asctime)s | %(name)s | %(levelname)s | %(message)s')
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/logging/__init__.py", line 1984, in basicConfig
    h = FileHandler(filename, mode)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/restapi.log'
/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/openordermv: Operation not permitted
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv: No such file or directory
bash: ~/Desktop/openordermv.sh: No such file or directory
bash: /Users/danielsutter/Desktop/openordermv.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/openordermv.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/openordermv.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/dailyrun.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/dailyrun.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/dailyrun.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/dailyrun.sh: Operation not permitted
/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
The file /Users/danielsutter/Desktop/open does not exist.
The file /Users/danielsutter/Desktop/open does not exist.
bash: /Users/danielsutter/Desktop/dailyrun.sh: Operation not permitted
bash: /Users/danielsutter/Desktop/dailyrun.sh: Operation not permitted
/bin/bash: /Users/danielsutter/Desktop/dailyrun.bash: Operation not permitted
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/credentials.json'"), ('/Users/danielsutter/Documents/oxide/scripts/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-25/dailyrun.bash'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/credentials.json'"), ('/Users/danielsutter/Documents/oxide/scripts/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/dailyrun.bash'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/credentials.json'"), ('/Users/danielsutter/Documents/oxide/scripts/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-29/dailyrun.bash'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-03-31/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-05/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-07/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-12/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-14/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-19/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-21/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-26/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-04-28/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-03/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-05/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-10/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-12/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-17/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-19/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-24/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-26/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-05-31/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-02/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-07/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-09/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-14/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-16/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-21/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-23/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-28/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-06-30/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-05/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-07/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-12/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-14/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-19/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-21/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-26/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-07-28/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 617, in <module>
    cfmp, sources, manf_names = main()
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 160, in main
    forecast_get = pd.read_excel(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1071, in __init__
    ext = inspect_excel_format(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 949, in inspect_excel_format
    with get_handle(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GoogleDrive/Shared drives/Docs/Operations/Production Forecast/Oxide Production Forecast.xlsx'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-02/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-04/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 617, in <module>
    cfmp, sources, manf_names = main()
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 160, in main
    forecast_get = pd.read_excel(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1071, in __init__
    ext = inspect_excel_format(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 949, in inspect_excel_format
    with get_handle(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GoogleDrive/Shared drives/Docs/Operations/Production Forecast/Oxide Production Forecast.xlsx'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-09/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-11/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 617, in <module>
    cfmp, sources, manf_names = main()
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 160, in main
    forecast_get = pd.read_excel(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1071, in __init__
    ext = inspect_excel_format(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 949, in inspect_excel_format
    with get_handle(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GoogleDrive/Shared drives/Docs/Operations/Production Forecast/Oxide Production Forecast.xlsx'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-16/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-18/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 617, in <module>
    cfmp, sources, manf_names = main()
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 160, in main
    forecast_get = pd.read_excel(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1071, in __init__
    ext = inspect_excel_format(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 949, in inspect_excel_format
    with get_handle(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GoogleDrive/Shared drives/Docs/Operations/Production Forecast/Oxide Production Forecast.xlsx'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-23/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-25/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 617, in <module>
    cfmp, sources, manf_names = main()
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 160, in main
    forecast_get = pd.read_excel(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1071, in __init__
    ext = inspect_excel_format(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 949, in inspect_excel_format
    with get_handle(
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/site-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/GoogleDrive/Shared drives/Docs/Operations/Production Forecast/Oxide Production Forecast.xlsx'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-08-30/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-01/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-13/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-15/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-20/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-22/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-27/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-09-29/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-04/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-06/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-11/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-13/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-18/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-20/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-25/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-10-27/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-01/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-03/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-08/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-10/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-15/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-17/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-22/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-24/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-11-29/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-01/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-06/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-08/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-13/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-15/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-20/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-22/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-27/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2022-12-29/credentials.json'")]
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/compforecast.py", line 21, in <module>
    import restapi as oxrest
ModuleNotFoundError: No module named 'restapi'
Traceback (most recent call last):
  File "/Users/danielsutter/Documents/oxide/scripts/local_weekly_backup.py", line 45, in <module>
    shutil.copytree(src_dir, dest_dir)
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/danielsutter/opt/anaconda3/envs/theasset/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/danielsutter/Documents/oxide/scripts/archive/23741457results.rtf', '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/archive/23741457results.rtf', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/archive/23741457results.rtf'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/dailyrun.bash', '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/archive/dailyrun.bash', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/archive/dailyrun.bash'"), ('/Users/danielsutter/Documents/oxide/scripts/archive/gitpush', '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/archive/gitpush', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/archive/gitpush'"), ('/Users/danielsutter/Documents/oxide/scripts/DURO-CATEGORY-REFERENCES.csv', '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/DURO-CATEGORY-REFERENCES.csv', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/DURO-CATEGORY-REFERENCES.csv'"), ('/Users/danielsutter/Documents/oxide/scripts/creds.yml', '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/creds.yml', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/creds.yml'"), ('/Users/danielsutter/Documents/oxide/scripts/credentials.json', '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/credentials.json', "[Errno 22] Invalid argument: '/Volumes/GoogleDrive/My Drive/scripts/backup2023-01-03/credentials.json'")]
